name: "zigbridge"
description: "Addon для создания виртуальных Zigbee устройств для возможности взаимодействия с HA через другие zigbee шлюзы"
version: 0.0.2
slug: "zigbridge"
uart: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
panel_icon: mdi:zigbee
ingress: true
timeout: 30
map:
  - addon_config:rw
ports:
  8099/tcp: null
homeassistant_api: true